services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bdapps_android_academy_app
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This allows container to access host

  nginx:
    image: nginx:alpine
    container_name: bdapps_android_academy_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge